name: Check Commit Messages

on:
  push:
    branches:
      - main
      - develop
      - release
      
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Commitizen
        run: pip install commitizen

      - name: Run Commitizen Check
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          elif [ "${{ github.event_name }}" == "push" ]; then
            cz check --rev-range ${{ github.event.before }}..${{ github.sha }}
          fi

  check-branch-name:
    name: Check Branch Name
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Run Commitizen Branch Check
        run: |
          BRANCH_NAME="${{ github.head_ref }}"

          if [[ ! "$BRANCH_NAME" =~ ^(main|develop|feature|bugfix|hotfix|release|refactor|docs|chore) ]]; then
            echo "❌ 分支命名不符合规范：$BRANCH_NAME"
            exit 1
          fi
